# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /afs/cern.ch/alice/offline/.@sys/local/bin/cmake

# The command to remove a file.
RM = /afs/cern.ch/alice/offline/.@sys/local/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /afs/cern.ch/alice/offline/.@sys/local/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /afs/cern.ch/user/a/azaborow/GEANT4/FCC-fast-sim

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /afs/cern.ch/user/a/azaborow/GEANT4/FCC-fast-sim

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/afs/cern.ch/alice/offline/.@sys/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/afs/cern.ch/alice/offline/.@sys/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/afs/cern.ch/alice/offline/.@sys/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/afs/cern.ch/alice/offline/.@sys/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/afs/cern.ch/alice/offline/.@sys/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/afs/cern.ch/alice/offline/.@sys/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /afs/cern.ch/user/a/azaborow/GEANT4/FCC-fast-sim/CMakeFiles /afs/cern.ch/user/a/azaborow/GEANT4/FCC-fast-sim/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /afs/cern.ch/user/a/azaborow/GEANT4/FCC-fast-sim/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Par01

# Build rule for target.
Par01: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Par01
.PHONY : Par01

# fast build rule for target.
Par01/fast:
	$(MAKE) -f CMakeFiles/Par01.dir/build.make CMakeFiles/Par01.dir/build
.PHONY : Par01/fast

#=============================================================================
# Target rules for targets named examplePar01

# Build rule for target.
examplePar01: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 examplePar01
.PHONY : examplePar01

# fast build rule for target.
examplePar01/fast:
	$(MAKE) -f CMakeFiles/examplePar01.dir/build.make CMakeFiles/examplePar01.dir/build
.PHONY : examplePar01/fast

examplePar01.o: examplePar01.cc.o
.PHONY : examplePar01.o

# target to build an object file
examplePar01.cc.o:
	$(MAKE) -f CMakeFiles/examplePar01.dir/build.make CMakeFiles/examplePar01.dir/examplePar01.cc.o
.PHONY : examplePar01.cc.o

examplePar01.i: examplePar01.cc.i
.PHONY : examplePar01.i

# target to preprocess a source file
examplePar01.cc.i:
	$(MAKE) -f CMakeFiles/examplePar01.dir/build.make CMakeFiles/examplePar01.dir/examplePar01.cc.i
.PHONY : examplePar01.cc.i

examplePar01.s: examplePar01.cc.s
.PHONY : examplePar01.s

# target to generate assembly for a file
examplePar01.cc.s:
	$(MAKE) -f CMakeFiles/examplePar01.dir/build.make CMakeFiles/examplePar01.dir/examplePar01.cc.s
.PHONY : examplePar01.cc.s

src/Par01ActionInitialization.o: src/Par01ActionInitialization.cc.o
.PHONY : src/Par01ActionInitialization.o

# target to build an object file
src/Par01ActionInitialization.cc.o:
	$(MAKE) -f CMakeFiles/examplePar01.dir/build.make CMakeFiles/examplePar01.dir/src/Par01ActionInitialization.cc.o
.PHONY : src/Par01ActionInitialization.cc.o

src/Par01ActionInitialization.i: src/Par01ActionInitialization.cc.i
.PHONY : src/Par01ActionInitialization.i

# target to preprocess a source file
src/Par01ActionInitialization.cc.i:
	$(MAKE) -f CMakeFiles/examplePar01.dir/build.make CMakeFiles/examplePar01.dir/src/Par01ActionInitialization.cc.i
.PHONY : src/Par01ActionInitialization.cc.i

src/Par01ActionInitialization.s: src/Par01ActionInitialization.cc.s
.PHONY : src/Par01ActionInitialization.s

# target to generate assembly for a file
src/Par01ActionInitialization.cc.s:
	$(MAKE) -f CMakeFiles/examplePar01.dir/build.make CMakeFiles/examplePar01.dir/src/Par01ActionInitialization.cc.s
.PHONY : src/Par01ActionInitialization.cc.s

src/Par01CalorimeterHit.o: src/Par01CalorimeterHit.cc.o
.PHONY : src/Par01CalorimeterHit.o

# target to build an object file
src/Par01CalorimeterHit.cc.o:
	$(MAKE) -f CMakeFiles/examplePar01.dir/build.make CMakeFiles/examplePar01.dir/src/Par01CalorimeterHit.cc.o
.PHONY : src/Par01CalorimeterHit.cc.o

src/Par01CalorimeterHit.i: src/Par01CalorimeterHit.cc.i
.PHONY : src/Par01CalorimeterHit.i

# target to preprocess a source file
src/Par01CalorimeterHit.cc.i:
	$(MAKE) -f CMakeFiles/examplePar01.dir/build.make CMakeFiles/examplePar01.dir/src/Par01CalorimeterHit.cc.i
.PHONY : src/Par01CalorimeterHit.cc.i

src/Par01CalorimeterHit.s: src/Par01CalorimeterHit.cc.s
.PHONY : src/Par01CalorimeterHit.s

# target to generate assembly for a file
src/Par01CalorimeterHit.cc.s:
	$(MAKE) -f CMakeFiles/examplePar01.dir/build.make CMakeFiles/examplePar01.dir/src/Par01CalorimeterHit.cc.s
.PHONY : src/Par01CalorimeterHit.cc.s

src/Par01CalorimeterSD.o: src/Par01CalorimeterSD.cc.o
.PHONY : src/Par01CalorimeterSD.o

# target to build an object file
src/Par01CalorimeterSD.cc.o:
	$(MAKE) -f CMakeFiles/examplePar01.dir/build.make CMakeFiles/examplePar01.dir/src/Par01CalorimeterSD.cc.o
.PHONY : src/Par01CalorimeterSD.cc.o

src/Par01CalorimeterSD.i: src/Par01CalorimeterSD.cc.i
.PHONY : src/Par01CalorimeterSD.i

# target to preprocess a source file
src/Par01CalorimeterSD.cc.i:
	$(MAKE) -f CMakeFiles/examplePar01.dir/build.make CMakeFiles/examplePar01.dir/src/Par01CalorimeterSD.cc.i
.PHONY : src/Par01CalorimeterSD.cc.i

src/Par01CalorimeterSD.s: src/Par01CalorimeterSD.cc.s
.PHONY : src/Par01CalorimeterSD.s

# target to generate assembly for a file
src/Par01CalorimeterSD.cc.s:
	$(MAKE) -f CMakeFiles/examplePar01.dir/build.make CMakeFiles/examplePar01.dir/src/Par01CalorimeterSD.cc.s
.PHONY : src/Par01CalorimeterSD.cc.s

src/Par01DetectorConstruction.o: src/Par01DetectorConstruction.cc.o
.PHONY : src/Par01DetectorConstruction.o

# target to build an object file
src/Par01DetectorConstruction.cc.o:
	$(MAKE) -f CMakeFiles/examplePar01.dir/build.make CMakeFiles/examplePar01.dir/src/Par01DetectorConstruction.cc.o
.PHONY : src/Par01DetectorConstruction.cc.o

src/Par01DetectorConstruction.i: src/Par01DetectorConstruction.cc.i
.PHONY : src/Par01DetectorConstruction.i

# target to preprocess a source file
src/Par01DetectorConstruction.cc.i:
	$(MAKE) -f CMakeFiles/examplePar01.dir/build.make CMakeFiles/examplePar01.dir/src/Par01DetectorConstruction.cc.i
.PHONY : src/Par01DetectorConstruction.cc.i

src/Par01DetectorConstruction.s: src/Par01DetectorConstruction.cc.s
.PHONY : src/Par01DetectorConstruction.s

# target to generate assembly for a file
src/Par01DetectorConstruction.cc.s:
	$(MAKE) -f CMakeFiles/examplePar01.dir/build.make CMakeFiles/examplePar01.dir/src/Par01DetectorConstruction.cc.s
.PHONY : src/Par01DetectorConstruction.cc.s

src/Par01EMShowerModel.o: src/Par01EMShowerModel.cc.o
.PHONY : src/Par01EMShowerModel.o

# target to build an object file
src/Par01EMShowerModel.cc.o:
	$(MAKE) -f CMakeFiles/examplePar01.dir/build.make CMakeFiles/examplePar01.dir/src/Par01EMShowerModel.cc.o
.PHONY : src/Par01EMShowerModel.cc.o

src/Par01EMShowerModel.i: src/Par01EMShowerModel.cc.i
.PHONY : src/Par01EMShowerModel.i

# target to preprocess a source file
src/Par01EMShowerModel.cc.i:
	$(MAKE) -f CMakeFiles/examplePar01.dir/build.make CMakeFiles/examplePar01.dir/src/Par01EMShowerModel.cc.i
.PHONY : src/Par01EMShowerModel.cc.i

src/Par01EMShowerModel.s: src/Par01EMShowerModel.cc.s
.PHONY : src/Par01EMShowerModel.s

# target to generate assembly for a file
src/Par01EMShowerModel.cc.s:
	$(MAKE) -f CMakeFiles/examplePar01.dir/build.make CMakeFiles/examplePar01.dir/src/Par01EMShowerModel.cc.s
.PHONY : src/Par01EMShowerModel.cc.s

src/Par01EnergySpot.o: src/Par01EnergySpot.cc.o
.PHONY : src/Par01EnergySpot.o

# target to build an object file
src/Par01EnergySpot.cc.o:
	$(MAKE) -f CMakeFiles/examplePar01.dir/build.make CMakeFiles/examplePar01.dir/src/Par01EnergySpot.cc.o
.PHONY : src/Par01EnergySpot.cc.o

src/Par01EnergySpot.i: src/Par01EnergySpot.cc.i
.PHONY : src/Par01EnergySpot.i

# target to preprocess a source file
src/Par01EnergySpot.cc.i:
	$(MAKE) -f CMakeFiles/examplePar01.dir/build.make CMakeFiles/examplePar01.dir/src/Par01EnergySpot.cc.i
.PHONY : src/Par01EnergySpot.cc.i

src/Par01EnergySpot.s: src/Par01EnergySpot.cc.s
.PHONY : src/Par01EnergySpot.s

# target to generate assembly for a file
src/Par01EnergySpot.cc.s:
	$(MAKE) -f CMakeFiles/examplePar01.dir/build.make CMakeFiles/examplePar01.dir/src/Par01EnergySpot.cc.s
.PHONY : src/Par01EnergySpot.cc.s

src/Par01ParallelWorldForPion.o: src/Par01ParallelWorldForPion.cc.o
.PHONY : src/Par01ParallelWorldForPion.o

# target to build an object file
src/Par01ParallelWorldForPion.cc.o:
	$(MAKE) -f CMakeFiles/examplePar01.dir/build.make CMakeFiles/examplePar01.dir/src/Par01ParallelWorldForPion.cc.o
.PHONY : src/Par01ParallelWorldForPion.cc.o

src/Par01ParallelWorldForPion.i: src/Par01ParallelWorldForPion.cc.i
.PHONY : src/Par01ParallelWorldForPion.i

# target to preprocess a source file
src/Par01ParallelWorldForPion.cc.i:
	$(MAKE) -f CMakeFiles/examplePar01.dir/build.make CMakeFiles/examplePar01.dir/src/Par01ParallelWorldForPion.cc.i
.PHONY : src/Par01ParallelWorldForPion.cc.i

src/Par01ParallelWorldForPion.s: src/Par01ParallelWorldForPion.cc.s
.PHONY : src/Par01ParallelWorldForPion.s

# target to generate assembly for a file
src/Par01ParallelWorldForPion.cc.s:
	$(MAKE) -f CMakeFiles/examplePar01.dir/build.make CMakeFiles/examplePar01.dir/src/Par01ParallelWorldForPion.cc.s
.PHONY : src/Par01ParallelWorldForPion.cc.s

src/Par01PhysicsList.o: src/Par01PhysicsList.cc.o
.PHONY : src/Par01PhysicsList.o

# target to build an object file
src/Par01PhysicsList.cc.o:
	$(MAKE) -f CMakeFiles/examplePar01.dir/build.make CMakeFiles/examplePar01.dir/src/Par01PhysicsList.cc.o
.PHONY : src/Par01PhysicsList.cc.o

src/Par01PhysicsList.i: src/Par01PhysicsList.cc.i
.PHONY : src/Par01PhysicsList.i

# target to preprocess a source file
src/Par01PhysicsList.cc.i:
	$(MAKE) -f CMakeFiles/examplePar01.dir/build.make CMakeFiles/examplePar01.dir/src/Par01PhysicsList.cc.i
.PHONY : src/Par01PhysicsList.cc.i

src/Par01PhysicsList.s: src/Par01PhysicsList.cc.s
.PHONY : src/Par01PhysicsList.s

# target to generate assembly for a file
src/Par01PhysicsList.cc.s:
	$(MAKE) -f CMakeFiles/examplePar01.dir/build.make CMakeFiles/examplePar01.dir/src/Par01PhysicsList.cc.s
.PHONY : src/Par01PhysicsList.cc.s

src/Par01PiModel.o: src/Par01PiModel.cc.o
.PHONY : src/Par01PiModel.o

# target to build an object file
src/Par01PiModel.cc.o:
	$(MAKE) -f CMakeFiles/examplePar01.dir/build.make CMakeFiles/examplePar01.dir/src/Par01PiModel.cc.o
.PHONY : src/Par01PiModel.cc.o

src/Par01PiModel.i: src/Par01PiModel.cc.i
.PHONY : src/Par01PiModel.i

# target to preprocess a source file
src/Par01PiModel.cc.i:
	$(MAKE) -f CMakeFiles/examplePar01.dir/build.make CMakeFiles/examplePar01.dir/src/Par01PiModel.cc.i
.PHONY : src/Par01PiModel.cc.i

src/Par01PiModel.s: src/Par01PiModel.cc.s
.PHONY : src/Par01PiModel.s

# target to generate assembly for a file
src/Par01PiModel.cc.s:
	$(MAKE) -f CMakeFiles/examplePar01.dir/build.make CMakeFiles/examplePar01.dir/src/Par01PiModel.cc.s
.PHONY : src/Par01PiModel.cc.s

src/Par01PionShowerModel.o: src/Par01PionShowerModel.cc.o
.PHONY : src/Par01PionShowerModel.o

# target to build an object file
src/Par01PionShowerModel.cc.o:
	$(MAKE) -f CMakeFiles/examplePar01.dir/build.make CMakeFiles/examplePar01.dir/src/Par01PionShowerModel.cc.o
.PHONY : src/Par01PionShowerModel.cc.o

src/Par01PionShowerModel.i: src/Par01PionShowerModel.cc.i
.PHONY : src/Par01PionShowerModel.i

# target to preprocess a source file
src/Par01PionShowerModel.cc.i:
	$(MAKE) -f CMakeFiles/examplePar01.dir/build.make CMakeFiles/examplePar01.dir/src/Par01PionShowerModel.cc.i
.PHONY : src/Par01PionShowerModel.cc.i

src/Par01PionShowerModel.s: src/Par01PionShowerModel.cc.s
.PHONY : src/Par01PionShowerModel.s

# target to generate assembly for a file
src/Par01PionShowerModel.cc.s:
	$(MAKE) -f CMakeFiles/examplePar01.dir/build.make CMakeFiles/examplePar01.dir/src/Par01PionShowerModel.cc.s
.PHONY : src/Par01PionShowerModel.cc.s

src/Par01PrimaryGeneratorAction.o: src/Par01PrimaryGeneratorAction.cc.o
.PHONY : src/Par01PrimaryGeneratorAction.o

# target to build an object file
src/Par01PrimaryGeneratorAction.cc.o:
	$(MAKE) -f CMakeFiles/examplePar01.dir/build.make CMakeFiles/examplePar01.dir/src/Par01PrimaryGeneratorAction.cc.o
.PHONY : src/Par01PrimaryGeneratorAction.cc.o

src/Par01PrimaryGeneratorAction.i: src/Par01PrimaryGeneratorAction.cc.i
.PHONY : src/Par01PrimaryGeneratorAction.i

# target to preprocess a source file
src/Par01PrimaryGeneratorAction.cc.i:
	$(MAKE) -f CMakeFiles/examplePar01.dir/build.make CMakeFiles/examplePar01.dir/src/Par01PrimaryGeneratorAction.cc.i
.PHONY : src/Par01PrimaryGeneratorAction.cc.i

src/Par01PrimaryGeneratorAction.s: src/Par01PrimaryGeneratorAction.cc.s
.PHONY : src/Par01PrimaryGeneratorAction.s

# target to generate assembly for a file
src/Par01PrimaryGeneratorAction.cc.s:
	$(MAKE) -f CMakeFiles/examplePar01.dir/build.make CMakeFiles/examplePar01.dir/src/Par01PrimaryGeneratorAction.cc.s
.PHONY : src/Par01PrimaryGeneratorAction.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Par01"
	@echo "... edit_cache"
	@echo "... examplePar01"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... examplePar01.o"
	@echo "... examplePar01.i"
	@echo "... examplePar01.s"
	@echo "... src/Par01ActionInitialization.o"
	@echo "... src/Par01ActionInitialization.i"
	@echo "... src/Par01ActionInitialization.s"
	@echo "... src/Par01CalorimeterHit.o"
	@echo "... src/Par01CalorimeterHit.i"
	@echo "... src/Par01CalorimeterHit.s"
	@echo "... src/Par01CalorimeterSD.o"
	@echo "... src/Par01CalorimeterSD.i"
	@echo "... src/Par01CalorimeterSD.s"
	@echo "... src/Par01DetectorConstruction.o"
	@echo "... src/Par01DetectorConstruction.i"
	@echo "... src/Par01DetectorConstruction.s"
	@echo "... src/Par01EMShowerModel.o"
	@echo "... src/Par01EMShowerModel.i"
	@echo "... src/Par01EMShowerModel.s"
	@echo "... src/Par01EnergySpot.o"
	@echo "... src/Par01EnergySpot.i"
	@echo "... src/Par01EnergySpot.s"
	@echo "... src/Par01ParallelWorldForPion.o"
	@echo "... src/Par01ParallelWorldForPion.i"
	@echo "... src/Par01ParallelWorldForPion.s"
	@echo "... src/Par01PhysicsList.o"
	@echo "... src/Par01PhysicsList.i"
	@echo "... src/Par01PhysicsList.s"
	@echo "... src/Par01PiModel.o"
	@echo "... src/Par01PiModel.i"
	@echo "... src/Par01PiModel.s"
	@echo "... src/Par01PionShowerModel.o"
	@echo "... src/Par01PionShowerModel.i"
	@echo "... src/Par01PionShowerModel.s"
	@echo "... src/Par01PrimaryGeneratorAction.o"
	@echo "... src/Par01PrimaryGeneratorAction.i"
	@echo "... src/Par01PrimaryGeneratorAction.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

